package com.ossprj.transmission.config;

import java.util.Arrays;
import java.util.List;

public interface TorrentConfiguration {

    List<String> TORRENT_FIELDS = Arrays.asList(
            "activityDate",
            "addedDate",
            "bandwidthPriority",
            "comment",
            "corruptEver",
            "creator",
            "dateCreated",
            "desiredAvailable",
            "doneDate",
            "downloadDir",
            "downloadedEver",
            "downloadLimit",
            "downloadLimited",
            "editDate",
            "error",
            "errorString",
            "eta",
            "etaIdle",
            "file-count",
            "files",
            "fileStats",
            "hashString",
            "haveUnchecked",
            "haveValid",
            "honorsSessionLimits",
            "id",
            "isFinished",
            "isPrivate",
            "isStalled",
            "labels",
            "leftUntilDone",
            "magnetLink",
            "manualAnnounceTime",
            "maxConnectedPeers",
            "metadataPercentComplete",
            "name",
            "peer-limit",
            "peers",
            "peersConnected",
            "peersFrom",
            "peersGettingFromUs",
            "peersSendingToUs",
            "percentDone",
            "pieces",
            "pieceCount",
            "pieceSize",
            "priorities",
            "primary-mime-type",
            "queuePosition",
            "rateDownload",
            "rateUpload",
            "recheckProgress",
            "secondsDownloading",
            "secondsSeeding",
            "seedIdleLimit",
            "seedIdleMode",
            "seedRatioLimit",
            "seedRatioMode",
            "sizeWhenDone",
            "sizeWhenDone",
            "startDate",
            "status",
            "trackerStats",
            "uploadRatio",
            "wanted",
            "webseeds",
            "webseedsSendingToUs"
    );
}
